Add a Dev Servers category with http-server and live-server
RyanZim/awesome-npm-scripts pull request #5
Opened 2016-10-06 15:56 UTC by maxlath

fixed #2

2016-10-06 17:31 UTC, RyanZim requested changes
Couple of nitpicks, other than that, LGTM. Thanks!

2016-10-06 17:31 UTC, RyanZim commented on README.md
> +- [Dev Servers](#doc-servers)
Typo here, use `npm run doctoc` to automatically & correctly generate a TOC.

2016-10-06 17:31 UTC, RyanZim commented on README.md
> +- [live-server](https://github.com/tapio/live-server) - Simple development http server with live reload capability
Please end lines with a full stop (`.`).

2016-10-06 17:43 UTC, maxlath commented on README.md
> +- [Dev Servers](#doc-servers)
I tried to run use `npm run doctoc` but for a reason I can't find, it always come back to the state before my edit, even after having manually edited the ToC oO

2016-10-06 17:50 UTC, RyanZim commented on README.md
> +- [Dev Servers](#doc-servers)
Did you save your changes to the file first?

2016-10-06 17:50 UTC, RyanZim approved these changes

2016-10-06 17:51 UTC, merged

2016-10-07 12:51 UTC, RyanZim commented
@maxlath Confirmed the buggy doctoc behavior, issue filed: https://github.com/thlorenz/doctoc/issues/121.